export const blogFullData = [
  { id: 1, thumb: "1.jpg", thumbFull: "1-full.jpg", title: "Announcing if attachment resolution sentiments.", date: { day: "25", month: "Aug", year: "2025" }, author: "Md Sohag", comments: 2, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 2, thumb: "3.jpg", thumbFull: "3-full.jpg", title: "Minuter him own clothes but observe as country.", date: { day: "26", month: "Aug", year: "2025" }, author: "Md Sohag", comments: 12, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 3, thumb: "2.jpg", thumbFull: "2-full.jpg", title: "Overcame breeding point concerns has terminate.", date: { day: "08", month: "Dec", year: "2025" }, author: "Md Sohag", comments: 45, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 4, thumb: "4.jpg", thumbFull: "4-full.jpg", title: "Announcing if attachment resolution sentiments.", date: { day: "28", month: "Sep", year: "2025" }, author: "Admin", comments: 33, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 5, thumb: "8.jpg", thumbFull: "8-full.jpg", title: "Minuter him own clothes but observe as country.", date: { day: "22", month: "Aug", year: "2025" }, author: "Admin", comments: 66, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 6, thumb: "9.jpg", thumbFull: "9-full.jpg", title: "Overcame breeding point concerns has terminate.", date: { day: "08", month: "Dec", year: "2025" }, author: "Admin", comments: 68, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 7, thumb: "8.jpg", thumbFull: "8-full.jpg", title: "Minuter him own clothes but observe as country.", date: { day: "22", month: "Aug", year: "2025" }, author: "Admin", comments: 66, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 8, thumb: "4.jpg", thumbFull: "4-full.jpg", title: "Announcing if attachment resolution sentiments.", date: { day: "28", month: "Sep", year: "2025" }, author: "Admin", comments: 33, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
  { id: 9, thumb: "2.jpg", thumbFull: "2-full.jpg", title: "Overcame breeding point concerns has terminate.", date: { day: "08", month: "Dec", year: "2025" }, author: "Md Sohag", comments: 45, description: "Indulgence diminution so discovered mr apartments. Are off under folly death wrote cause her way spite. Plan upon yet way get cold spot its week." },
];
